"""init

Revision ID: c5c0448564d0
Revises: 
Create Date: 2018-04-23 15:59:30.964481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c0448564d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CartItem',
    sa.Column('cartItemID', sa.Integer(), nullable=False),
    sa.Column('SKU', sa.Integer(), nullable=False),
    sa.Column('cartID', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cartItemID')
    )
    op.create_table('Customer',
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phoneNum', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('customerID')
    )
    op.create_index(op.f('ix_Customer_email'), 'Customer', ['email'], unique=True)
    op.create_table('Product',
    sa.Column('SKU', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('storage_location', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('SKU')
    )
    op.create_index(op.f('ix_Product_name'), 'Product', ['name'], unique=True)
    op.create_table('PurchaseOrder',
    sa.Column('poID', sa.Integer(), nullable=False),
    sa.Column('cartID', sa.Integer(), nullable=False),
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.Column('totalOrderPrice', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('createdDt', sa.DateTime(), nullable=True),
    sa.Column('lastUpdatedDt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('poID')
    )
    op.create_index(op.f('ix_PurchaseOrder_createdDt'), 'PurchaseOrder', ['createdDt'], unique=False)
    op.create_index(op.f('ix_PurchaseOrder_lastUpdatedDt'), 'PurchaseOrder', ['lastUpdatedDt'], unique=False)
    op.create_table('ShoppingCart',
    sa.Column('cartID', sa.Integer(), nullable=False),
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cartID')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('Address',
    sa.Column('addressID', sa.Integer(), nullable=False),
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.Column('line1', sa.String(length=100), nullable=False),
    sa.Column('line2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('zipCode', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['customerID'], ['Customer.customerID'], ),
    sa.PrimaryKeyConstraint('addressID')
    )
    op.create_table('CreditCard',
    sa.Column('creditCardID', sa.Integer(), nullable=False),
    sa.Column('customerID', sa.Integer(), nullable=False),
    sa.Column('ccCompany', sa.String(length=100), nullable=False),
    sa.Column('ccNum', sa.String(length=30), nullable=False),
    sa.Column('ccExpDt', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['customerID'], ['Customer.customerID'], ),
    sa.PrimaryKeyConstraint('creditCardID')
    )
    op.create_table('ProductBatch',
    sa.Column('batchID', sa.Integer(), nullable=False),
    sa.Column('SKU', sa.Integer(), nullable=False),
    sa.Column('batch_quantity', sa.Integer(), nullable=False),
    sa.Column('batch_expiration', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SKU'], ['Product.SKU'], ),
    sa.PrimaryKeyConstraint('batchID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProductBatch')
    op.drop_table('CreditCard')
    op.drop_table('Address')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_table('User')
    op.drop_table('ShoppingCart')
    op.drop_index(op.f('ix_PurchaseOrder_lastUpdatedDt'), table_name='PurchaseOrder')
    op.drop_index(op.f('ix_PurchaseOrder_createdDt'), table_name='PurchaseOrder')
    op.drop_table('PurchaseOrder')
    op.drop_index(op.f('ix_Product_name'), table_name='Product')
    op.drop_table('Product')
    op.drop_index(op.f('ix_Customer_email'), table_name='Customer')
    op.drop_table('Customer')
    op.drop_table('CartItem')
    # ### end Alembic commands ###
